---
- name: systemd-daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable-firstboot-services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - bigfix-firstboot.service
    - rapid7-firstboot.service
    - cortex-xdr-firstboot.service

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
